data: 
  name: volleyball
  sendo_dataset_dir : data/volleyball_tracking_annotation
  rgb_dataset_dir : data/videos
  annotation_dir : data/vatic_ball_annotation/annotation_data/
  dataset_bbox_gt: data/jae_dataset_bbox_gt
  dataset_bbox_pred: data/jae_dataset_bbox_pred

exp_set:
  save_folder: saved_weights
  # wandb_name: volleyball-hgtd_bbox_GT_gaze_GT_act_GT
  wandb_name: volleyball-hgtd_bbox_PRED_gaze_PRED_act_PRED
  wandb_log : True

  batch_size: 2
  num_workers: 1
  seed_num: 777
  gpu_mode : True
  gpu_start : 5
  gpu_finish : 5

  # resize_height: 320
  resize_height: 224
  # resize_width: 480
  resize_width: 224
  resize_head_height: 64
  resize_head_width: 64

exp_params:

  use_frame_type: mid
  # use_frame_type: all

  # bbox_types: GT
  bbox_types: PRED

  # gaze_types: GT
  gaze_types: PRED
  
  # action_types: GT
  action_types: PRED

  # learning rate
  lr : 0.00001

  # position augmentation
  use_position_aug: False
  # use_position_aug: True
  position_aug_std: 0.05

  # gt gaussian
  gaussian_sigma: 10

  # learning schedule
  nEpochs : 500
  start_iter : 0
  snapshots : 100
  scheduler_start : 1000
  scheduler_iter : 1100000

  # pretrained models
  pretrained_models_dir: saved_weights

  use_pretrained_joint_attention_estimator: False
  # use_pretrained_head_pose_estimator: True
  pretrained_joint_attention_estimator_name: pretrain_head_estimator
  freeze_joint_attention_estimator: False
  # freeze_joint_attention_estimator: True

model_params:
  model_type: human_gaze_target_transformer