data: 
  name: videocoatt
  dataset_dir : data/VideoCoAtt_Dataset
  saliency_dataset_dir : data/deepgaze_output_loader

exp_set:
  save_folder: saved_weights
  # wandb_name: videocoatt-concat_independent_w_davt_scene
  wandb_name: videocoatt-concat_direct_w_davt_scene
  wandb_log : True

  # batch_size: 16
  batch_size: 8
  # batch_size: 2
  # batch_size: 1
  num_workers: 16
  seed_num: 777
  gpu_mode : True
  gpu_start : 4
  gpu_finish : 4

  resize_height: 320
  resize_width: 480
  resize_head_height: 64
  resize_head_width: 64

exp_params:
  use_gaze_loss : False
  # use_gaze_loss : True

  use_e_map_loss : False
  # use_e_map_loss : True

  use_e_att_loss : False
  # use_e_att_loss : True

  # use_each_e_map_loss : False
  use_each_e_map_loss : True

  use_regression_loss : False
  # use_regression_loss : True

  use_regression_not_att_loss : False
  # use_regression_not_att_loss : True

  use_attraction_loss : False
  # use_attraction_loss : True

  use_repulsion_loss : False
  # use_repulsion_loss : True
  
  use_frame_type: mid
  # use_frame_type: all
  
  use_gt_gaze: False
  # use_gt_gaze: True

  # position augmentation
  use_position_aug: False
  # use_position_aug: True
  position_aug_std: 0.05

  # loss function
  loss : mse
  # loss : bce

  # learning rate
  lr : 0.0001

  # gt gaussian
  gaussian_sigma: 10

  # learning schedule
  nEpochs : 500
  start_iter : 0
  snapshots : 100
  scheduler_start : 1000
  scheduler_iter : 1100000

  det_heads_model : dets_txt_nk_faster_rcnn_20220421
  # train_det_heads : False
  train_det_heads : True
  train_heads_conf : 0.6
  test_heads_conf : 0.6

  # pretrained models
  pretrained_models_dir: saved_weights

  # use_pretrained_head_pose_estimator: False
  use_pretrained_head_pose_estimator: True
  pretrained_head_pose_estimator_name: videocoatt-head_pose_estimator
  # freeze_head_pose_estimator: False
  freeze_head_pose_estimator: True

  # use_pretrained_saliency_extractor: False
  use_pretrained_saliency_extractor: True
  pretrained_saliency_extractor_name: pretrained_scene_extractor_davt
  # freeze_saliency_extractor: False
  freeze_saliency_extractor: True

  use_pretrained_joint_attention_estimator: False
  # use_pretrained_head_pose_estimator: True
  pretrained_joint_attention_estimator_name: pretrain_head_estimator
  freeze_joint_attention_estimator: False
  # freeze_joint_attention_estimator: True

model_params:
  model_type: ja_transformer

  # Position
  # use_position : False
  use_position : True
  use_position_enc_person : False
  # use_position_enc_person : True
  use_position_enc_type : sine
  # use_position_enc_type : learnable

  # Gaze
  # use_gaze : False
  use_gaze : True
  gaze_type: vector
  # gaze_type: feature

  # Action
  use_action : False
  # use_action : True

  # Person embedding
  # head_embedding_type : liner
  head_embedding_type : mlp
  # head_embedding_type : ident
  # head_embedding_type : each

  # Whole image
  # use_img : False
  use_img : True

  use_attention_map_rgb : False
  # use_attention_map_rgb : True

  # Gaze map
  use_angle_dist_rgb_type : none
  # use_angle_dist_rgb_type : raw
  # use_angle_dist_rgb_type : feat

  use_dynamic_angle : False
  # use_dynamic_angle : True

  # use_dynamic_distance : False
  use_dynamic_distance : True

  # dynamic_distance_type: gaussian
  # dynamic_gaussian_num : 1
  dynamic_distance_type: generator
  use_gauss_limit : False
  # use_gauss_limit : True

  gaze_map_estimator_type : identity
  # gaze_map_estimator_type : normal
  # gaze_map_estimator_type : deep

  # transformer
  # use_people_people_trans: False
  use_people_people_trans: True

  rgb_people_trans_type : concat_direct
  # rgb_people_trans_type : concat_paralell
  # rgb_people_trans_type : concat_independent

  people_people_trans_enc_num : 1
  mha_num_heads_people_people : 2

  rgb_people_trans_enc_num : 1
  mha_num_heads_rgb_people : 2
  rgb_embeding_dim : 64
  people_feat_dim : 16

  # rgb_cnn_extractor_type : normal
  # rgb_cnn_extractor_type : no_use
  # rgb_cnn_extractor_type : saliency
  rgb_cnn_extractor_type : scene_davt
  # rgb_cnn_extractor_type : rgb_patch
  # rgb_cnn_extractor_type : resnet18
  # rgb_cnn_extractor_type : resnet50
  # rgb_cnn_extractor_stage_idx : 1
  # rgb_cnn_extractor_stage_idx : 2
  # rgb_cnn_extractor_stage_idx : 3
  # rgb_cnn_extractor_stage_idx : 4
  # rgb_cnn_extractor_type : hrnet_w18_small
  # rgb_cnn_extractor_type : hrnet_w32
  # rgb_cnn_extractor_stage_idx : 3
  # rgb_cnn_extractor_type : convnext
  # rgb_cnn_extractor_stage_idx : 2

  # angle_distance_fusion: max
  # angle_distance_fusion: mean
  angle_distance_fusion: mult