data: 
  name: videocoatt
  dataset_dir : data/VideoCoAtt_Dataset
  saliency_dataset_dir : data/deepgaze_output_loader

exp_set:
  save_folder: saved_weights
  wandb_name: videocoatt-isa
  wandb_log : True

  batch_size: 16
  num_workers: 16
  seed_num: 777
  gpu_mode : True
  gpu_start : 3
  gpu_finish : 3

  # resize_height: 320
  resize_height: 28
  # resize_width: 480
  resize_width: 28
  resize_head_height: 64
  resize_head_width: 64

exp_params:
  # use_e_att_loss : False
  use_e_att_loss : True

  use_frame_type: mid
  # use_frame_type: all

  use_gt_gaze: False
  # use_gt_gaze: True

  # position augmentation
  use_position_aug: False
  # use_position_aug: True
  position_aug_std: 0.05

  # loss function
  # loss : mse
  loss : bce

  # learning rate
  lr : 0.0001

  # gt gaussian
  gaussian_sigma: 10

  # learning schedule
  nEpochs : 500
  start_iter : 0
  snapshots : 100
  scheduler_start : 1000
  scheduler_iter : 1100000

  det_heads_model : dets_txt_nk_faster_rcnn_20220421
  train_det_heads : False
  # train_det_heads : True
  train_heads_conf : 0.6
  test_heads_conf : 0.6

  # pretrained models
  pretrained_models_dir: saved_weights

  # use_pretrained_head_pose_estimator: False
  use_pretrained_head_pose_estimator: True
  pretrained_head_pose_estimator_name: videocoatt-head_pose_estimator
  # freeze_head_pose_estimator: False
  freeze_head_pose_estimator: True

  use_pretrained_joint_attention_estimator: False
  # use_pretrained_head_pose_estimator: True
  pretrained_joint_attention_estimator_name: pretrain_head_estimator
  freeze_joint_attention_estimator: False
  # freeze_joint_attention_estimator: True

model_params:
  model_type: isa