data: 
  name: videoattentiontarget
  dataset_dir : data/videoattentiontarget

exp_set:
  save_folder: saved_weights
  # wandb_name: videoattentiontarget-hgt
  wandb_name: videoattentiontarget-hgt-high

  wandb_log : True

  batch_size: 16
  num_workers: 16
  seed_num: 777
  gpu_mode : True
  gpu_start : 5
  gpu_finish : 5

  # resize_height: 320
  resize_height: 224
  # resize_width: 480
  resize_width: 224
  resize_head_height: 64
  resize_head_width: 64

exp_params:
  # learning rate
  lr : 0.00001

  # gt gaussian
  gaussian_sigma: 40

  # learning schedule
  nEpochs : 500
  start_iter : 0
  snapshots : 100
  scheduler_start : 1000
  scheduler_iter : 1100000

  # pretrained models
  pretrained_models_dir: saved_weights

  use_pretrained_joint_attention_estimator: False
  # use_pretrained_head_pose_estimator: True
  pretrained_joint_attention_estimator_name: pretrain_head_estimator
  freeze_joint_attention_estimator: False
  # freeze_joint_attention_estimator: True

model_params:
  model_type: human_gaze_target_transformer